### ISSUE TITLE
Suggestion of caching list of channels  

### ISSUE THREAD

**Issue by zedatgithub** [cralin/plugin.video.DigiOnline.ro#1]
Building the list of channels dynamically use time when you just move between categories

suggestion to add a kind of caching for X minute

**Comment by cralin** [comment]
Hi,

Yes indeed, it takes more time than having a hard-coded list of channels
but it brings the benefit of less maintenance required in the add-on.

If you already have an idea on how to implement the caching you've
mentioned, please open a pull-request with the changes you propose.
I'd be more than happy to merge it as long is it does not break the
existing functionality or makes tings worse than they are already.

**Comment by cralin** [comment]
PR merged
