### ISSUE TITLE
EPG xml nu poate fi afisat daca contine tag-uri invalide

### ISSUE THREAD

**Issue by rapi3** [cralin/plugin.video.DigiOnline.ro#12]
Se poate intimpla ca EPG-ul downloadat sa contina in descrierea programului secvente de forma < text >.
Rezultatul va fi ca intreg fisierul xml nu va putea fi incarcat si afisat deoarece este invalid.
IPTV va genera eroare:
**ERROR: AddOnLog: PVR IPTV Simple Client: Unable parse EPG XML: expected =**

Problema in fisierul atasat este: <Toy Story 16>
[EPG -bad.zip](https://github.com/cralin/plugin.video.DigiOnline.ro/files/4689455/EPG.-bad.zip)

**Comment by cralin** [comment]
Fixed in 1.0.9.

- Sterge fisierul "plugin.video.DigiOnline.ro.EPG.xml"
- Instaleaza versiunea 1.0.9, dupa instalare se creeaza automat fisierul "plugin.video.DigiOnline.ro.EPG.xml"
- Dupa ce e creat "plugin.video.DigiOnline.ro.EPG.xml", restart la kodi ca sa fortezi PVR IPTV Simple client sa citeasca din nou fisierul XMLTV.

**Comment by rapi3** [comment]
Super rapid l-ati rezolvat. **_Felicitari !_**

Desi in IPTV apare **Timers** si **Timer rules**, nu par sa fie functionale: "_The PVR backend does not support timers_"
Intrebare: 
Stiti cumva daca exista vre-un addon care sa permita switch pe canal IPTV la ora H ?
Ideal ar fi sa poti defini mutiple timere direct din ghid/epg.

**Comment by cralin** [comment]
In cazul acesta particular, "backend"-ull pentru PVR IPTV Simple Client e
addon-ul el insasi.

Evident ca acest addon nu este gindit (prin urmare nu este nici
implementat) ca un sistem PVR complet functional care are toate
functionalitatile pe care le gasesti pe un PVR comercial.
