### ISSUE TITLE
EPG - empty

### ISSUE THREAD

**Issue by rapi3** [cralin/plugin.video.DigiOnline.ro#14]
Am sesizat o situatie in care EPG-ul este aproape gol. Nu stiu daca din cauza ca nu este actualizat pe server sau s-a modificat ceva la ei in sistem.
Se poate implementa o verificare a lungimii fisierului nou EPG creat si daca este < 100kb sa ramana valabil fisierul vechi ( pana acum un fisier EPG ok este >2Mb ) si sa reincerce regenerarea lui dupa un interval de timp ~1h ?
[EPG-empty.zip](https://github.com/cralin/plugin.video.DigiOnline.ro/files/4715098/EPG-empty.zip)

**Comment by cralin** [comment]
Refresh-ul se face o data pe zi la ora setata in sectiunea "Simple PVR Integration" din setarile addon-ului. 
La fiecare refresh de EPG se fac doua request-uri pentru fiecare canal: 
- EPG pentru data curenta (ziua de azi)
- EPG pentru data curenta (ziua de azi) + o zi (ziua de miine).  

EPG-ul este gol fiindca (virgula) cimpul in care ar trebui sa fie informatiile respective este gol in raspunsul primit pentru de la server pentru data de 2 iunie si pentru data de 3 iunie.

Se pare ca pentru data de 2 si 3 iunie cimpurile cu datele EPG sint goale cam la toate canalele in afara de Digi Sport [1234].

Ieri a fost 1 Iunie (Ziua Copilului) si probabil ca si "copiii" care se ocupa de actualizarea acestor date au avut liber la fel ca restul copiilor din Romania.

**Comment by cralin** [comment]
Poti oricind sa schimbi in setari ora cind se actualizeaza EPG data.

**Comment by rapi3** [comment]
l-am rezolvat mai elegant:

1 - am modificat serviciul ca sa re-creeze automat fisierul EPG daca cumva este sters, deci addon-ul nu mai trebuie repornit manual.

in def schedule_jobs(): am modificat:
`  else:`
`    _ENVHOME_DIR_ = xbmc.translatePath('special://envhome')`
`    _epg_file_ = os.path.join(_ENVHOME_DIR_, vars.__SimplePVRIntegration_EPG_FileName__)`
`    if os.path.exists(_epg_file_) and os.path.getsize(_epg_file_) != 0:`
`      # The _epg_file_ exists and is not empty.`
`      logger.debug('Nothing to do !')`
`    else:`
`      # The _epg_file_ does not exist any more or is empty.`
`      logger.debug('\'' + _epg_file_ + '\' does not exist or is empty.')`
`      SimplePVRIntegration_init_EPG_file(vars.__ServiceID__, vars.__AddonCookieJar__, vars.__ServiceSession__, MyServiceAddon_DataDir)`
`  logger.debug('Exit function')`

2 - am creat in cron la fiecare 60 min sa ruleze scriptul care verifica mariumea EPG
crontab -e
`#Sterge EPG daca este <200k`
`*/60 * * * * /storage/epg-size.sh`

3 - am creat scriptul care verifica si sterge EPG daca este mic:
/storage/epg-size.sh
`#!/bin/bash`
`file=/storage/plugin.video.DigiOnline.ro.EPG.xml`
`minimumsize=200000`
`actualsize=$(wc -c <"$file")`
`if [ $actualsize -ge $minimumsize ]; then`
`exit`
`else`
`rm /storage/file=plugin.video.DigiOnline.ro.EPG.xml`
`fi`
`exit`
