### ISSUE TITLE
Kodi in windows 7 rulat ca user -> eroare nu poate crea fisierele epg si m3u

### ISSUE THREAD

**Issue by rapi3** [cralin/plugin.video.DigiOnline.ro#17]
Am testat Kodi in windows 7 x64 ruland ca si user ( nu ca administrator ) si am sesizat ca nu poate crea fisierele m3u si xml.
Deoarece foloseste:
`_ENVHOME_DIR_ = xbmc.translatePath('special://envhome')`
acesta este mapat de Kodi-win in C:\Program files\Kodi\ ( dir de instalare a Kodi ) si normal utilizatorul simplu nu are drepturi de scriere in acel dir.
Este un risc de securitate sa rulezi ca administrator sau sa dai drepturi depline in acel dir asa ca probabil fisierele xml si m3u ar trebui mutate in alt dir.

**Comment by cralin** [comment]
Windows are multe probleme si prin urmare cam tot ce ruleaza pe Windows are de asemenea probleme. 
Mai mult de atit, Windows 7 este EOL cam de pe la inceputul anului 2020.

Sfatul meu este sa folosesti altceva (Linux + Kodi sau Libreelec direct pe hardware ?) decit Windows pentru a rula Kodi.

**Comment by rapi3** [comment]
Sunt in situatia in care nu se poate instala kodi pe linux-ul de zi cu zi  ( MX-18.3 ) si fiind multi-boot cu win deocamdata imi este mai simplu sa inlocuiesc in service.py decit sa fac update sau sa modific partitiile ca sa instalez si un LEx86:
`os.path.join(_ENVHOME_DIR_  -> os.path.join(MyServiceAddon_DataDir`

**Comment by cralin** [comment]
Eu personal nu folosesc Windows si nici nu imi planuiesc sa o fac in viitorul apropiat.

In service.py inlocuieste "special://envhome" cu "special://userdata" si verifica daca iti creaza fisierele in profilul userului de Windows.

Daca sint create in Windows in directorul unde are userul profilul (si sint create corect chiar daca nu au user cu drepturi de administrator) da-mi un reply in thread-ul acesta.

Multumesc.

**Comment by rapi3** [comment]
**special://userdata** va crea fisierele in **.kodi/userdata/**
atit in Linux cat si in Windows ( este corect localizat in dir cu profilul userului unde sunt toate datele de la kodi si userul are drepturile depline ),
Acum ramane discutabil daca nu este mai bine de tinut datele in **MyServiceAddon_DataDir** la fel ca si cache-ul cu posturile addonului decit sa fie raspandite prin tot kodi-ul, eu unul optez pentru **MyServiceAddon_DataDir**

**Comment by cralin** [comment]
Cele doua fisiere sint acum scrise intr-un director separat din addon data dir.
In cursul zilei de azi mai vin citeva commit-uri cu link-uri inspre wiki unde e documentat cum se instaleaza/configureaza PVR IPTV Simple Client ca sa functioneze cu add-on-ul si apoin tagging si release.

Pina atunci, poti sa testezi cu o copie din master care are deja modificarile pentru locatia fisierelor m3u si XMLTV.

**Comment by rapi3** [comment]
este ok
- sugestie: daca vrei sa faci numele directorului mai mic deoarece in windows este limitare la 260 caractere numele maxim in Path; preventiv sa nu apara probleme in cazuri speciale in care numele userului este mare (economisesti 13 caractere din 116 cat are acum si arata mai bine).
PVRIPTVSimpleClientIntegration -> PVRIPTV

**Comment by rapi3** [comment]
In windows python nu poate redenumi fisierul tmp in xml daca exista, xml trebuie sters inainte.

```2020-06-11 08:20:50.428 T:2808   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.WindowsError'>
                                            Error Contents: [Error 183] Cannot create a file when that file already exists
                                            Traceback (most recent call last):
                                              File "C:\Users\user1\AppData\Roaming\Kodi\addons\plugin.video.DigiOnline.ro\service.py", line 438, in <module>
                                                schedule.run_pending()
                                              File "C:\Users\user1\AppData\Roaming\Kodi\addons\plugin.video.DigiOnline.ro\resources\lib\schedule\__init__.py", line 582, in run_pending
                                                default_scheduler.run_pending()
                                              File "C:\Users\user1\AppData\Roaming\Kodi\addons\plugin.video.DigiOnline.ro\resources\lib\schedule\__init__.py", line 97, in run_pending
                                                self._run_job(job)
                                              File "C:\Users\user1\AppData\Roaming\Kodi\addons\plugin.video.DigiOnline.ro\resources\lib\schedule\__init__.py", line 150, in _run_job
                                                ret = job.run()
                                              File "C:\Users\user1\AppData\Roaming\Kodi\addons\plugin.video.DigiOnline.ro\resources\lib\schedule\__init__.py", line 485, in run
                                                ret = self.job_func()
                                              File "C:\Users\user1\AppData\Roaming\Kodi\addons\plugin.video.DigiOnline.ro\service.py", line 140, in schedule_jobs
                                                PVRIPTVSimpleClientIntegration_init_EPG_file(vars.__ServiceID__, vars.__AddonCookieJar__, vars.__ServiceSession__, MyServiceAddon_DataDir)
                                              File "C:\Users\user1\AppData\Roaming\Kodi\addons\plugin.video.DigiOnline.ro\service.py", line 294, in PVRIPTVSimpleClientIntegration_init_EPG_file
                                                PVRIPTVSimpleClientIntegration_update_EPG_file(NAME, COOKIEJAR, SESSION, DATA_DIR)
                                              File "C:\Users\user1\AppData\Roaming\Kodi\addons\plugin.video.DigiOnline.ro\service.py", line 416, in PVRIPTVSimpleClientIntegration_update_EPG_file
                                                os.rename(_tmp_epg_file_, _epg_file_)
                                            WindowsError: [Error 183] Cannot create a file when that file already exists
                                            -->End of Python script error report<--```

**Comment by rapi3** [comment]
patch:
```    _data_file_.close()
    if os.path.isfile(_m3u_file_):    
       os.remove(_m3u_file_)
    os.rename(_tmp_m3u_file_, _m3u_file_)
...
       _data_file_.close()
    if os.path.isfile(_epg_file_):    
       os.remove(_epg_file_)
    os.rename(_tmp_epg_file_, _epg_file_)

**Comment by cralin** [comment]
Cu riscul de a ma repeta:
Windows are o gramada de probleme si prin urmare cam tot ce ruleaza pe
Windows are probleme.

Dupa cum vezi, o simpla operatie de rename care ar trebui sa fie atomica si
care in orice alt system de operare _este_ atomica si functioneaza corect
intr-un singur pas/ciclu CPU, pe Windows nu functioneaza in mod atomic prin
urmare esti obligat sa scrii degeaba cod suplimentar care care duce la
ineficienta (consum inutil de cicluri CPU pentru o operatie simpla) si pe
deasupra implica si executia inutila de cod pe restul platformelor care au
reusit sa implementeze corect operatia de rename.

Sfatul meu este sa folosesti altceva in loc de Windows.

Un Raspberry Pi3 cu un SD card de 8G si un alimentator de curent costa cam
50-55 EUR in functie de dealer-ul de la care il cumperi.
