### ISSUE TITLE
Nu pornesc stream-urile pe Mi Box cu Android TV

### ISSUE THREAD

**Issue by danxtrate** [cralin/plugin.video.DigiOnline.ro#20]
L-am instalat pe un Mi Box actualizat la zi cu Kodi 18 si stream-urile nu pornesc. Par sa porneasca dar dispar imediat. 
Am instalat si PVR Simple client si desi am gasit folderul pentru add-on, nu exista folderul PVRIPTVSimpleClientIntegration.

**Comment by cralin** [comment]
Te rog sa:
1) Descarci [de aici](https://github.com/cralin/plugin.video.DigiOnline.ro) codul add-onului (click pe butonul verde pe care scrie "Code" si alegi "Download zip").
2) Instaleazi add-onul din zip-ul descarcat la pasul 1
3) In configuratia add-onului activeaza optiunea "Enable debug logging" (ADD-ONS -> My add-ons -> Video add-ons -> DigiOnline.ro -> Configure -> General settings)
4) restart la device
5) Porneste un canal din lista
6) ataseaza aici urmatoarele fisiere log generate de addon:
  `/.kodi/userdata/addon_data/plugin.video.DigiOnline.ro/plugin.video.DigiOnline.ro.log
/.kodi/userdata/addon_data/plugin.video.DigiOnline.ro/service.plugin.video.DigiOnline.ro.log`

**Comment by danxtrate** [comment]
[plugin.video.DigiOnline.ro.zip](https://github.com/cralin/plugin.video.DigiOnline.ro/files/5298948/plugin.video.DigiOnline.ro.zip)
Iata-le!

**Comment by cralin** [comment]
Te rog sa activezi si [ kodi debug logging](https://kodi.wiki/view/Settings/System/Logging#Debug).
si tot pe aceeasi pagina este si "component logging", de acolo activeaza si "Enable component-specific logging" si alege "Verbose logging for the  libcURL library".

Trafic din nou la ceva canale si apoi adauga si fisierul "~/.kodi/temp/kodi.log"

Multumesc

**Comment by cralin** [comment]
Te rog sa folosesti codul addon-ului de aici: https://github.com/cralin/plugin.video.DigiOnline.ro (branch-ul "master")

- Descarci de codul add-onului (click pe butonul verde pe care scrie "Code" si alegi "Download zip").
- Instaleazi add-onul din zip-ul descarcat la pasul anterior.

**Comment by danxtrate** [comment]
Asta nu e bun? 
https://github.com/cralin/plugin.video.DigiOnline.ro/releases/tag/1.0.15

Reinstalez atunci si revin.

**Comment by cralin** [comment]
trimite kodi.log dupe ce ai activat debug logging in kodi si ai mai facut ceva trafic pe la ceva canale.

**Comment by danxtrate** [comment]
[kodi.log.zip](https://github.com/cralin/plugin.video.DigiOnline.ro/files/5299370/kodi.log.zip)
poate asta e gherla: " ERROR: OpenDemuxStream - Error creating demuxer"

**Comment by cralin** [comment]
Activeaza in kodi debug logging si component logging la LibCURL inainte sa incerci sa faci play la canale.

In log-ul atasat scrie ca debug logging e dezactivat.

**2020-09-29 16:19:38.656 T:6396  NOTICE: Disabled debug logging due to GUI setting. Level 0.**
2020-09-29 16:19:38.656 T:6396  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
2020-09-29 16:19:51.180 T:6396   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2020-09-29 16:20:02.237 T:6396  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.DigiOnline.ro/?action=play&channel_metadata=%7B%22shortcode%22%3A%22livestream%22%2C%22new-info%22%3A%7B%22meta%22%3A%7B%22scope%22%3A%22digi24%22%2C%22start%22%3A%22%22%2C%22stop%22%3A%22%22%2C%22message%22%3A%22%22%2C%22channelName%22%3A%22Digi24%22%2C%22streamUrl%22%3A%22%5C%2Fapi%5C%2Fstream%22%2C%22streamId%22%3A4%2C%22abr%22%3Atrue%2C%22balancerKey%22%3A%223535ce748b5f846d1a8a385c007d9e12%22%2C%22loggedIn%22%3Atrue%7D%7D%7D&channel_endpoint=%2Fstiri%2Fdigi24
2020-09-29 16:20:02.239 T:7066  NOTICE: Creating InputStream
2020-09-29 16:20:02.240 T:7066  NOTICE: Creating Demuxer
2020-09-29 16:20:02.771 T:7066   ERROR: OpenDemuxStream - Error creating demuxer

**Comment by danxtrate** [comment]
[kodi.log (1).zip](https://github.com/cralin/plugin.video.DigiOnline.ro/files/5299696/kodi.log.1.zip)
Back again. 
Cumva la stream ajunge, ca la HBO mi-a zis ca trebuie sa am user si parola ca sa ma uit.

**Comment by cralin** [comment]
Descarca codul addon-ului de aici: https://github.com/cralin/plugin.video.DigiOnline.ro (branch-ul "master") si instaleaza-l.

Dupa update-ul addon-ului: 
- verifica sa ai in continuare debug logging enabled atit in sectiunea de configurare a addon-ului cit si in sectiunea de configurare a Kodi-ului (la kodi pastreaza activata si "Enable component-specific logging" impreuna cu "Verbose logging for the libcURL library").
- restart la device
- porneste un canal care nu este cu DRM (digi24)

Ar trebui sa-ti spuna ca ai nevoie de InputStream Adaptive si sa te intrebe daca vrei sa-l instalezi.

Confirmi ca vrei sa-l instalezi si dupa instalare ar trebui sa-ti faca play la stream.

Daca nu iti face play atunci adauga noile fisiere log generate atit de add-on cit si de Kodi:
`~/.kodi/userdata/addon_data/plugin.video.DigiOnline.ro/plugin.video.DigiOnline.ro.log`
`~/.kodi/userdata/addon_data/plugin.video.DigiOnline.ro/service.plugin.video.DigiOnline.ro.log`
`~/.kodi/temp/kodi.log`

**Comment by cralin** [comment]
Iti zic sa descarci codul add-onului din branch-ul "master" fiidca tocmai am facut commit cu modificari in cod care ar trebui sa rezolve problema ta.

**Comment by danxtrate** [comment]
am vazut ca ai facut commit, acum da alta eroare "Invalid repetitve credentials". 
Parola am verificat-o de cateva ori, ca sa fiu sigur ca nu o pun aiurea. 
[plugin.video.DigiOnline.ro.log.zip](https://github.com/cralin/plugin.video.DigiOnline.ro/files/5300626/plugin.video.DigiOnline.ro.log.zip)
[kodi.log (2).zip](https://github.com/cralin/plugin.video.DigiOnline.ro/files/5300627/kodi.log.2.zip)

**Comment by cralin** [comment]
Te-a intrebat de instalarea InputStream Adapter ?

Faci enable si la "Enable component-specific logging" impreuna cu "Verbose logging for the libcURL library" inainte sa pornesti un canal si imi trimiti kodi.log care sa aiba log entries si de la libraria libcURL atunci cind incersi sa faci play la un canal ?

**Comment by cralin** [comment]
nici in plugin.video.DigiOnline.ro.log nu este nimic logat in debug level.

**Comment by danxtrate** [comment]
am logging-urile pornite, am verificat inainte sa ii dau drumu. Mai incerc odata. Daca nu, fresh install de Kodi si vedem

**Comment by danxtrate** [comment]
Rezolvata problema cu autentificarea. La fiecare schimbare de add-on DigiOnline inregistreaza un dispozitiv nou. Le-am dezactivat din cont si acum merge sa se logheze. 

Uite si un video cu modul in care se manifesta, am incercat si un pe un MiBox S care statea degeaba, cu fresh install. 
https://drive.google.com/file/d/11TCgcgJ8Q-U7vafkkklTGYZH4CPV11GY/view?usp=sharing
[kodi.log (3).zip](https://github.com/cralin/plugin.video.DigiOnline.ro/files/5300860/kodi.log.3.zip)
[plugin.video.DigiOnline.ro.log (1).zip](https://github.com/cralin/plugin.video.DigiOnline.ro/files/5300861/plugin.video.DigiOnline.ro.log.1.zip)

[kodi.log (3).zip](https://github.com/cralin/plugin.video.DigiOnline.ro/files/5300850/kodi.log.3.zip)
[plugin.video.DigiOnline.ro.log (1).zip](https://github.com/cralin/plugin.video.DigiOnline.ro/files/5300851/plugin.video.DigiOnline.ro.log.1.zip)

**Comment by cralin** [comment]
Uite asa trebuie sa arate in Kodi setarile de debug logging:

libcURL trebuie sa fie portocaliu (selectat in lista) inainte sa apesi OK

![01](https://user-images.githubusercontent.com/47091655/94596968-3bb08300-028d-11eb-9a09-b5179169708d.png)
![02](https://user-images.githubusercontent.com/47091655/94596976-3eab7380-028d-11eb-895b-907b09a23eb0.png)

**Comment by danxtrate** [comment]
Asa is si la mine. Doar ca-s cu verde, de la tema.

**Comment by cralin** [comment]
Asa trebuie sa arate si in configuratia addon-ului:

![03](https://user-images.githubusercontent.com/47091655/94602896-c7c6a880-0295-11eb-8dcb-2e0671279d71.png)



Dupa care incerci sa pornesti un canal, si daca nu merge play, ataseaza toate trei fisiere (complete) cu log-uri.

**Comment by danxtrate** [comment]
iata-le
[kodi.log](https://github.com/cralin/plugin.video.DigiOnline.ro/files/5305051/kodi.log)
[plugin.video.DigiOnline.ro.log](https://github.com/cralin/plugin.video.DigiOnline.ro/files/5305052/plugin.video.DigiOnline.ro.log)
[service.plugin.video.DigiOnline.ro.log](https://github.com/cralin/plugin.video.DigiOnline.ro/files/5305053/service.plugin.video.DigiOnline.ro.log)

**Comment by cralin** [comment]
Nu vad in kodi.log nici un mesaj care sa arate "DEBUG: Curl::Debug"
Te rog activeaza in kodi sa faca logging la toate componentele.

In "plugin.video.digionline.ro.log" si nici in "service.plugin.digionline.ro.log" atasate de tine azi nu ai mesaje cu DEBUG ci ai doar mesaje cu INFO.
Ori nu ai activat in configuratia addon-ului asa cum arata aici: https://github.com/cralin/plugin.video.DigiOnline.ro/issues/20#issuecomment-700916487 ori nu ai atasat aici fisiere luate de pe masina pe care ai aplicat configurarea respectiva.

**Comment by danxtrate** [comment]
[kodi.log](https://github.com/cralin/plugin.video.DigiOnline.ro/files/5311034/kodi.log)

Acu e bine? Se dezactiveaza Debug logging-ul din add-on la fiecare restart.

**Comment by cralin** [comment]
Salut,

Inainte de (t)eroara ca nu poate sa deschida fisierul m3u8 ar trebui sa se vada si detaliile request-ului trimis pentru download-ul acelui fisier de pe la edge210.rcs-rds.ro.


```
2020-10-01 11:10:59.386 T:7746   DEBUG: CPlayerGUIInfo::InitCurrentItem(plugin://plugin.video.DigiOnline.ro/?action=play&channel_metadata=%7B%22shortcode%22%3A%22livestream%22%2C%22new-info%22%3A%7B%22meta%22%3A%7B%22scope%22%3A%22digi24%22%2C%22start%22%3A%22%22%2C%22stop%22%3A%22%22%2C%22message%22%3A%22%22%2C%22channelName%22%3A%22Digi24%22%2C%22streamUrl%22%3A%22%5C%2Fapi%5C%2Fstream%22%2C%22streamId%22%3A4%2C%22abr%22%3Atrue%2C%22balancerKey%22%3A%221759e3098550a0ac48618a7165290bce%22%2C%22loggedIn%22%3Atrue%7D%7D%7D&channel_endpoint=%2Fstiri%2Fdigi24)
2020-10-01 11:10:59.388 T:19907   DEBUG: Loading settings for plugin://plugin.video.DigiOnline.ro/?action=play&channel_metadata=%7B%22shortcode%22%3A%22livestream%22%2C%22new-info%22%3A%7B%22meta%22%3A%7B%22scope%22%3A%22digi24%22%2C%22start%22%3A%22%22%2C%22stop%22%3A%22%22%2C%22message%22%3A%22%22%2C%22channelName%22%3A%22Digi24%22%2C%22streamUrl%22%3A%22%5C%2Fapi%5C%2Fstream%22%2C%22streamId%22%3A4%2C%22abr%22%3Atrue%2C%22balancerKey%22%3A%221759e3098550a0ac48618a7165290bce%22%2C%22loggedIn%22%3Atrue%7D%7D%7D&channel_endpoint=%2Fstiri%2Fdigi24
2020-10-01 11:10:59.405 T:19918   DEBUG: Thread BackgroundLoader 19918 terminating
2020-10-01 11:10:59.415 T:7754   DEBUG: void CXBMCApp::OnPlayBackStarted()
2020-10-01 11:10:59.422 T:7754   DEBUG: Visible Behind request: false
2020-10-01 11:10:59.443 T:19914    INFO: Python interpreter stopped
2020-10-01 11:10:59.443 T:19914   DEBUG: Thread LanguageInvoker 19914 terminating
2020-10-01 11:10:59.487 T:7746   DEBUG: ------ Window Init (DialogBusy.xml) ------
2020-10-01 11:10:59.974 T:19917   DEBUG: Error, could not open file https://edge210.rcs-rds.ro/V4-5577029-14668e185c5d8af77692cd92ee5fb100-1835273065-0-1601539859-4-digi24/digi24/digi24-abr.m3u8?is=4&ns=digi24&p=Browser&s=site&sn=digionline.ro&t=00000000000000000000000000000000&t4=V4-5577029-14668e185c5d8af77692cd92ee5fb100-1835273065-0-1601539859-4-digi24
```

Activeaza te rog in debug logging toate modulele (aici: https://user-images.githubusercontent.com/47091655/94596976-3eab7380-028d-11eb-895b-907b09a23eb0.png) si fara sa-i mai dai restart porneste din nou acelasi stream.

**Comment by danxtrate** [comment]
![PXL_20201001_130526014 MP](https://user-images.githubusercontent.com/33743667/94813195-5eaf7400-0400-11eb-8222-844c955686ae.jpg)
[kodi.log](https://github.com/cralin/plugin.video.DigiOnline.ro/files/5312158/kodi.log)
[plugin.video.DigiOnline.ro.log](https://github.com/cralin/plugin.video.DigiOnline.ro/files/5312160/plugin.video.DigiOnline.ro.log)
[service.plugin.video.DigiOnline.ro.log](https://github.com/cralin/plugin.video.DigiOnline.ro/files/5312161/service.plugin.video.DigiOnline.ro.log)

**Comment by cralin** [comment]
Descarca te rog codul din branch-ul master si dupa ce l-ai instalat tine activate optiunile de debugging in kodi si verifica un stream fara DRM.

Daca nu merge, adauga fisierele log.
Daca merge, pune un comment aici ca sa stiu ca e rezolvata problema.

Multumesc.

**Comment by danxtrate** [comment]
Merg unele canalele, suspectez ca cele fara DRM. TLC, Eurosport nu merg, de exemplu.

**Comment by cralin** [comment]
Cele fara DRM trebuie sa mearga toate.
Testeaza si cu canale cu DRM.

Daca nu iti merg canale adauga la un thread nou og-urile cu debug enabled ca sa pot sa verific.

Versiunea 1.0.6 contine fix-urile care le-am facut pentru issue-ul acesta pina acum.
