### ISSUE TITLE
Feature: Navigation

### ISSUE THREAD

**Issue by nextshell** [cralin/plugin.video.DigiOnline.ro#5]
Hi There,
Great work with the dynamic channels and the plugging in general.

It seems to be taking a lot of time while navigating through the menu and this is probably 
because it's fetching for channels every time one is using the menu.

Not many people will have the patience to wait for it to load every time.

P.S. Perhaps a folder with all channels would be a quick fix.

Again, great work with the plugging.

**Comment by cralin** [comment]
Hi,

The v1.0.2 already includes a basic logic for caching the
categories/channels.
That's the quick-fix and that should help improve a little bit the things
in this area until I can complete the implementation of a better (more
optimal ?) approach to this problem.

I agree that it needs to be as fast as possible in showing on the screen
the list of categories/channels.
However, for me it makes no sense to show outdated, meaningless or
irrelevant data on the screen just for the sake of showing something fast.

There is a fine balancing act between having fresh data to be shown on the
screen (fresh data costs time as it has to be read using multiple web
requests) and the speed of showing something meaningful on the
screen/menus.
The addon will have a setting in the addon configuration to allow the user
to choose what he/she finds to be the best balance between those 2 options.

**Comment by cralin** [comment]
Hi,

The v1.0.3 should be faster in listing the categories and channels as long
as cached data is not yet expired.

Obviously, if you start with a fresh/new installation the list of
categories and the list of channels in each category will still have to be
queried from DigiOnline.ro before caching them locally for the duration of
the retention period.

You can now choose in the addon settings what is the best balance having
fresh data to be shown on the screen and the speed of showing the
screen/menus with channel lists at the cost of some outdated information
about the program title shown in the channel list.

I'm still not fully convinced that showing the program title in the channel
list is the best approach here.
It just takes too much time and too many requests to get from DigiOnline.ro
some data that will probably not be relevant anymore few minutes later.

**Comment by cralin** [comment]
Fixed with 1.0.3

**Comment by rapi3** [comment]
@nextshell 
![20200325_164355](https://user-images.githubusercontent.com/18531150/77556801-3aa33100-6eb9-11ea-807c-a4dbf42ff03b.jpg)
![20200325_164614](https://user-images.githubusercontent.com/18531150/77556817-3ecf4e80-6eb9-11ea-8fc0-73a610c3bdad.jpg)

**Comment by cralin** [comment]
Hi,
The version 1.0.5 now generates and maintain a playlist file that can be used by PVR IPTV Simple Client. 
It should help with navigating through channels in a similar way as on regular TV.

**Comment by cralin** [comment]
Srarting with version 1.0.7, the addon also generates and maintains the XMLTV file that can be used by PVR IPTV Simple Client.

Here are some screenshots:

![LibreELEC_26_05_2020_00_15_46](https://user-images.githubusercontent.com/47091655/82897762-6c3b8580-9f58-11ea-862f-5fbbe4db88a3.png)
![LibreELEC_26_05_2020_00_16_04](https://user-images.githubusercontent.com/47091655/82897783-75c4ed80-9f58-11ea-8450-f2e85cb65916.png)
![LibreELEC_26_05_2020_00_17_26](https://user-images.githubusercontent.com/47091655/82897786-79587480-9f58-11ea-91ad-485de15fdc58.png)

**Comment by rapi3** [comment]
Super.
Congratulation !
