### ISSUE TITLE
sugestie - afisare toate canalele disponibile sortate dupa categorie

### ISSUE THREAD

**Issue by rapi3** [cralin/plugin.video.DigiOnline.ro#7]
Felicitari pentru aceasta aplicatie !
Este cea mai buna disponibila in acest moment !

Deoarece navigarea este cam greoaie pentru TV ( sa tot iesi dintr-o categorie ca sa muti pe un canal in alta categorie ) se poate adauga optiune in setare sa afiseze toate posturile TV la un loc - sortate dupa categorie ( ex: filme-tematice-stiri-muzica...) sau eventual sa fie configurabila de utilizator ordinea categoriilor.

Multumesc.

**Comment by cralin** [comment]
Salut,

Poti te rog sa dai mai multe detalii ?

* Ai instalat si folosesti ultima versiune a add-on-ului (in acest moment
ultima versiune e 1.0.3) ?
* Pe ce device rulezi add-onul ?
  La mine merge pe un Raspberry Pi 3 cu un card SD banal de pe boot-eaza
LibreElec 9.2.1.

* Iti merge greu dupa prima instalare, la prima intrare intr-o categorie
sau iti merge greu si la urmatoarele intrari in aceeasi categorie ?
  Inplicit, la prima pornire, add-on-ul face caching la categoriile si
canalele disponibile in fiecare categorie iar durata de timp cit tine (si
foloseste) datele in cache poate fi configurata in setari.
  La a doua intrare in aceeasi categorie canalele vor fi afisate in cache
in loc sa le aduca de fiecare data de la DIgiOnline.ro si prin uramare ti
se vor afisa mai repede.

* Ai activata optiunea sa afiseze titlul programului in lista cu numele
canalelor ?
  Daca ai activata aceasta optiune, se mai trimita inca 1-2 request-uri la
DigiOnline.ro ca sa mai aduca si datele EPG pentru fiecare canal din
categoria in care ai intrat, ceea ce evident iti creste timpul de asteptare
pina iti arata lista cu canale.

**Comment by rapi3** [comment]
Salut,

Folosesc aplicatia pe un RPI3b care boot-eaza de pe stick USB LibreELEC 9.2.1.
Da am activata optiunea sa afiseze titlul programului...

Ma refer strict la modul de navigare in aplicatie cind doresti sa schimbi de pe un program activ pe altul care este in alta categorie.
de exemplu:
Folosec telecomanda televizorului LG conectata pe CEC-HDMI;
1- apas butonul verde imi apare lista de programe din categoria unde este postul la care ma uit (Filme).
2- navigez in alta categorie (Tematice) si trebuie sa mai astept 1-2-3... secunde sa afiseze lista de posturi din acea categorie ca sa pot selecta ce doresc; in acest interval se vede in fundal cum sacadeaza postul activ... se desincronizeaza.
Daca toate canalele ar fi in aceasi categorie ( cum este la plug-inul IPTV ) totul s-ar desfasura mai repede si probabil s-ar evita o incarcare a procesorului cu evitarea generari listei cu posturile din categoria in care intri.

**Comment by rapi3** [comment]
inca o situatie neplacuta. nu stiu daca se poate rezolva sau tine de Kodi:
in timp ce vizionez un program si vreau sa schimb pe altul ... apas butonul verde sau back si apare lista de programe; cum fac sa dispara lista daca renunt si vreau sa raman pe acelasi post ?
Daca tot dau exit ies din lista si ies si din addon si in final dispare dar la urmatoarea schimbare nu mai sunt in addon si trebuie sa intru in addon si apoi in lista de canale ca si cum as porni addon-ul.

**Comment by cralin** [comment]
Salut,

Addon-ul se foloseste de InputStream Adaptive pentru redarea stream-ului.
InputStream Adaptive alege calitatea stream-ului in functie de latimea de
banda pe care o ai la Internet (in special cit de reped poti sa downloadezi
ceva din internet) iar in cazul in care ~3-4 Mbit/s download speed o sa-ti
faca play la stream-ul cel mai bun.

Procesorul de la Raspberry Pi 3 e saturat complet daca trebuie sa faca
decodarea unui stream de calitate mare, stream HD sau mai mare.
Daca mai are de facut si altceva in paralel, de ex. download de la
DigiOnline.ro a listei de canale din categoria curenta, e deja peste ceea
ce poate sa faca si incepi sa vezi "stuttering effects" din cele pe care
le-ai descris.
Situatia e si mai nasoala daca nu ai activat hardware decoding si duce
repede la incalzirea procesorului ceea ce duce automat la CPU trottling din
cauza temperaturii ceea ce duce la scaderea si mai drastica a performantei
processorului

Asta nu are de a face cu add-on-ul ci mai degraba cu capabilitatile
hardware-ului pe care rulezi addon-ul si cu care faci play la stream.
Poti sa verifici cit de saturat e procesorul de la Raspberry daca pui pe
ecran System -> System Info -> Summary.

Ai mai multe optiuni, atit software cit si hardware, ca sa iti faci viata
ceva mai placuta din punctul acesta de vedere.

Software:
1) Cumpara-ti si activeaza-ti licentele pentru hardware decoding si
codec-uri aditionale:  https://swag.raspberrypi.org/collections/software
2) In setarile de la InputStream Adaptive (Addons -> My addons ->
InputStream Adaptive -> Configure) ajusteaza valorile pentru "Max.
Resolution general decoder" si "Max. Resolution secure decoder" la niste
valori mai mici.

Hardware:
1) Raspberry Pi 4 -> are processor mai rapid si prin urmare nu il mai
saturezi cu decodarea unui stream video HD. Consuma ceva mai mult curent
decit un raspberry Pi 3, disipa mai multa caldura ceea ce te va obliga sa
ii pui radiator de racire pe procesor si e alimentat prin port USB C in loc
de mini USB si asta inseamna ca nu mai poti sa folosesti alimentatorul de
la RPI3.
2) Barebone PC -> Intel NUC, Jetway JBC* sau Shuttle Barebone sint
platforme destul de puternice sa poata sa faca play la multiple stream-uri
HD in paralel, majoritatea sint fanless si sint totusi destul de mici ca sa
poata sa fie ascunse in spatele televizorului.


Eu personal am ales optiunea software, am activat licentele pentru hardware
decoding si am setate in InputStream Adaptive am setat ambele optiuni la
valoarea:  720p.

**Comment by rapi3** [comment]
Salut,

Foarte informativa si educativa postarea ta. Multumesc.

- Am setat refresh-ul de la 60Hz la 25Hz la rezolutia 1920x1080p si cred ca asta are cel mai mare impact asupra procesorului, acum aproape someaza inclusiv la stream-uri 1080p.
- InputStream Adaptive nu este instalat by default si nu il aveam instalat. L-am instalat manual dar l-am lasat pe default/maxim deocamdata.
- Am patch-uit start.elf ptr hw decoder (sa fie acolo chiar daca majoritatea stream-urilor sunt h264 si nu MPEG-2).
https://github.com/nucular/raspi-keygen/issues/6#issuecomment-601047147

Folosesti cumva pe vre-un smart tv SS IPTV ?
Ar fi super interesant un script python care sa genereze periodic link-urile intr-un fisier pe care sa-l foloseasca SS IPTV-ul. Asa scapi de orice alta limitare de hw si ai calitate maxima daca tv-ul face upscaling. Ce parere ai ? Te pot ajuta cu testarea.

**Comment by cralin** [comment]
Raspberry Pi 3 e hardware-ul care il folosesc zilnic atunci cind vreau sa
consum continut media online.
Acelasi hardware e folosit si pentru teste, prin urmare daca ceva nu merge
in codul add-on-ului "beneficiez" de feedback direct si foarte perturbator
legat de faptul ca nu functioneaza corect add-onul.

Ajutor cu testatul e binevenit oricind mai ales avind in vedere ca nu vreau
investesc in tot felul de hardware si nici nu am timpul necesar ca sa
testez toate combinatiile posibile care sint folosite de altii.

Inca nu am reusit sa testez daca merge corect cu streamurile HBO, HBO2.
HBO3 si FilmNow findca nu le am activate inca in contul meu DigiOnline si
nici nu cred ca am sa le am activate prea curind.
In principiu ar trebui sa functioneze fara nici o problema insa ar fi
foarte utila o confirmare si pentru respectivele streamuri.

**Comment by rapi3** [comment]
Nici eu nu am activat nici un fel de extra optiuni asa ca nu pot sa-ti spun deocamdata despre HBO-uri...

**Comment by rapi3** [comment]
Deocamdata modificarile sunt facute manual editand 2 fisiere deoarece cunostintele mele de python sunt limitate ( eu mi-am adaugat doar posturile dorite ):
in functia def update_cached_channels
se pot adauga usor citeva linii sa adauge orice canal nou si in channels__all__.json
_cache_data_all_file_ = os.path.join(DATA_DIR, vars.__cache_dir__, 'channels__all__.json')
...
mai trebuie adaugat in fisierul categories.json categoria All
{"name": "all", "title": "All"}

![20200325_164355](https://user-images.githubusercontent.com/18531150/77558739-9a9ad700-6ebb-11ea-9ed6-e964bf21205e.jpg)
![20200325_164614](https://user-images.githubusercontent.com/18531150/77558751-9d95c780-6ebb-11ea-96e8-012c700c1487.jpg)

**Comment by cralin** [comment]
Salut,

Addon-ul citeste de pe Digionline.ro lista de categorii si fiecare canal
din categoria selectata tocmai ca sa nu trebuiasca sa fie mentinute manual
in codul addon-ului de fiecare data cind se actualizata lista de canale si
categorii de catre proprietarul stream-urilor.

Cind te logezi cu browserul de web, ai in contul tau de pe www.DigiOnline.ro
categoria "All" ?

In orice caz, nu cred ca adaugarea artificiala de categorii suplimentare
este directia de urmat in acest addon.

**Comment by rapi3** [comment]
My Favorite = All ca sa fie primul afisat in lista, si scopul lui ptr mine este doar sa ma ajute sa navighez rapid in lista de canale la care ma uit eu; sa nu pierd 10 secunde cind mut de pe un post pe altul dintr-o categorie diferita.

**Comment by cralin** [comment]
Hi,
The version 1.0.5 now generates and maintain a playlist file that can be used by PVR IPTV Simple Client.
It should help with navigating through channels in a similar way as on regular TV.

**Comment by rapi3** [comment]
Super,
sugestie: salveaza fisierul generat m3u in videos asa va putea fi accesat si rulat si de acolo din interfata.
