### ISSUE TITLE
EPG data nu se actualizeaza automat.

### ISSUE THREAD

**Issue by rapi3** [cralin/plugin.video.DigiOnline.ro#8]
EPG data nu este actualizat daca ramai si vizionezi posturile doar dintr-o categorie.
Ex: Opresti canalul cu stop -> navighezi in lista neactualizata.
EPG se actualizeaza doar daca iesi din categoria respectiva si intrii din nou in ea sau daca intrii in alta categorie.

p.s.
Am impresia ca e bug Kodi daca nu are un parametru setabil cind sa faca refresh la lista primita spre afisare.

**Comment by cralin** [comment]
Works as designed/intended.

Citeste, in special capitlul 4 si capitolul 6, [de aici](https://kodi.wiki/view/About_Add-ons) ca sa intelegi cum/unde sint integrate in kodi addon-urile si cum functioneaza.
