### ISSUE TITLE
Actualizare pentru Kodi 19 - Python3

### ISSUE THREAD

**Issue by rapi3** [cralin/plugin.video.DigiOnline.ro#9]
Se poate actualiza codul pentru Python3 - Kodi19 ?
Dupa mici modificari am ajus in faza asta unde nu mai stiu sa-i dau de capat...
```ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: can only concatenate str (not "bytes") to str
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.DigiOnline.ro/main.py", line 602, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "/storage/.kodi/addons/plugin.video.DigiOnline.ro/main.py", line 575, in router
                                                       list_channels(params['category'])
                                                     File "/storage/.kodi/addons/plugin.video.DigiOnline.ro/main.py", line 262, in list_channels
                                                       _ch_epg_data_ = json.loads(functions.get_cached_epg_data(_ch_metadata_['new-info']['meta']['streamId'], vars.__AddonID__, vars.__AddonSession__, MyAddon_DataDir))
                                                     File "/storage/.kodi/addons/plugin.video.DigiOnline.ro/resources/lib/common/functions.py", line 748, in get_cached_epg_data
                                                       update_cached_epg_data(STREAM_ID, NAME, SESSION, DATA_DIR)
                                                     File "/storage/.kodi/addons/plugin.video.DigiOnline.ro/resources/lib/common/functions.py", line 693, in update_cached_epg_data
                                                       _epg_data_ = get_epg_data(STREAM_ID, NAME, SESSION)
                                                     File "/storage/.kodi/addons/plugin.video.DigiOnline.ro/resources/lib/common/functions.py", line 671, in get_epg_data
                                                       logger.debug('_epgdata_ = ' + _epgdata_)
                                                   TypeError: can only concatenate str (not "bytes") to str
                                                   -->End of Python script error report<--````

**Comment by cralin** [comment]
Salut,

Codul din branch-ul [feature/Kodi_19_Matrix](https://github.com/cralin/plugin.video.DigiOnline.ro/tree/feature/Kodi_19_Matrix)  pare sa ruleze pe un **Raspberry Pi 3** cu [LibreELEC (community): nightly=20200921-1fcfe6a](https://test.libreelec.tv/LibreELEC-RPi2.arm-9.80-nightly-20200921-1fcfe6a.img.gz) care include Kodi 19.0-ALPHA1(18.9.701)

Cel putin nu se mai blocheaza din cauza diferentelor majore (de sub capota) dintre Kodi 18 si Kodi 19.

Avind in vedere ca virgula Kodi 19 e inca in stadiul "Alpha" nu m-ar mira/surprinde sa mai fie ceva ce mi-a scapat sau care nu functioneaza asa cum ar trebui. 

Prin urmare:   A SE CONSUMA CU O DOZA MARE DE PRECAUTIE ! 

Daca gasesti questii care nu merg te rog sa adaugi un comment in thread-ul acesta cu niste log-uri si detalii despre platforma pe care nu merge si mai ales detalii despre ce nu merge.

Issue-ul acesta ramine deschis pina la primul release stabil de LibreELEC care include Kodi 19.

**Comment by rapi3** [comment]
Salut,
am pus in teste LibreELEC-RPi4.arm-9.80-nightly-20201001-85830fd si addon-ul tau merge OK.
Daca apare ceva suspect te anunt.

**Comment by cralin** [comment]
L-ai pus pe Raspberry Pi 4 si iti merge corect play-ul la audio/video ?
Nu are desincronizari intre audio si video ?

La mine pe RPI3 pare sa aiba desincronizare intre sunet si video. 
Cam cum erau pe vremuri filmele chinezesti, prima data il vezi ca vorbeste si apoi se aude si vocea.
:)
Am impresia ca RPI3 e la limita cu Python 3 sub capota LibreELEC

In schimb in VM (imaginea .ova) sau pe un laptop cu boot-at cu imaginea Generic face restart cind incerc sa instalez add-onul din zip.

**Comment by rapi3** [comment]
E pe RPI4 2G RAM si acum aMC nu pare sa fie desincronizat.
Cred ca depinde si de canalul pe care te uiti si de net, am prins o perioada in care AXN-ul seara  era desincronizat audio-video cu 1-2 secunde, restul canalelor nu si asta cu LE stabil.

**Comment by cralin** [comment]
Salut,

Am facut un repository ca sa se poata instala mai usor versiunile de add-on.

https://github.com/cralin/repository.cralin/blob/master/repository.cralin-1.0.0.zip

Deocamdata sint doar ultimele 3 versiuni cu addon-ul care merge pe Kodi 18 dar in curind va ajunge in repository si prima versiune care merge pe Kodi 19.

**Comment by cralin** [comment]
https://github.com/cralin/repository.cralin.Kodi_18/blob/master/repository.cralin.Kodi_18-1.0.0.zip

**Comment by cralin** [comment]
Repository pentru Kodi 19 (Matrix) aici:  https://github.com/cralin/repository.cralin.Kodi_19

**Comment by cralin** [comment]
Add-onul acesta este pe linie moarta. Nu va mai primi cod nou (functionalitati sau bugfix-uri) si urmeasa sa fie retras in viitorul apropiat.

[https://github.com/cralin/plugin.video.TVOnline.ro](https://github.com/cralin/plugin.video.TVOnline.ro) include toate functionalitatile acestui add-on si functioneaza cu Kodi 19 (Matrix).
